apiVersion: v1
kind: Service
metadata:
  name: weasel
  labels:
    app: weasel
spec:
  selector:
    app: weasel
  type: NodePort
  ports:
   - port: 5000
     nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weasel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weasel
  template:
    metadata:
      labels:
        app: weasel
        version: v1
    spec:
      containers:
        - name: weasel
          image: jor2/weasel:latest
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  type: NodePort
  ports:
   - port: 27017
     nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        version: v1
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
          - containerPort: 27017
